### ISSUE TITLE
new package design

### ISSUE THREAD

**Issue by pylat** [kul-forbes/CIAOAlgorithms#1]
Hi @lostella, @nantonel 
I am making this new package for stochastic and incremental methods using Iteratortools from ProximalAlgorithms.jl. So far Finito/MISO and SVRG/SVRG++ are implemented. 

One issue that I encountered for my own use of the package is that it is not very convenient to modify the solver for reporting purposes. I  essentially want to have a way to decouple the solver from reporting, and ideally to allow the user to take one iteration at a time while having access to the state or at least the updated solution. I have added the following:

    If `solver = Finito(args...)`, then 

    problem = Finito_problem(solver, F, g, x0, N, L)

    instantiate a struct `problem` with the following fields: 
        * `sol`:    the current output (initially equal to x0) 
        * `iter`:   the appropriate Finito iterator
        * `cnt`:    iteration number
        * `state`: the internal state of the solver   

    To perform one iteration of the algorithm specified with the solver run

    update!(problem)

    The fields of `problem` are updated accordingly.
    Note that irrelevant fields of the solver (maxit, verbose, freq) are ignored in this mode.      

So in this way one can simply use 
```
    for k = 1:maxit
        CIAOAlgorithms.update!(problem)
        # report using problem.sol
    end
```
 The code for doing this can be found at the last part of Finito.jl. If you have time, I would appreciate your feedback about my implementation. I suspect that there is be a better way of doing this. Any suggestion guys?

**Comment by lostella** [comment]
@pylat I think that once you have the iterated sequence encoded as an iterator you have all the flexibility you need for reporting. If the "output" of the iteration is the state (so essentially, the `iterate` function returns `state, state`, see ProximalAlgorithms) you can easily do whatever you want with it:

```julia
for state in iterator
    println(norm(state.residual))
    println(state.objective_value)
end
```

**Comment by pylat** [comment]
> @pylat I think that once you have the iterated sequence encoded as an iterator you have all the flexibility you need for reporting. If the "output" of the iteration is the state (so essentially, the `iterate` function returns `state, state`, see ProximalAlgorithms) you can easily do whatever you want with it:
> 
> ```julia
> for state in iterator
>     println(norm(state.residual))
>     println(state.objective_value)
> end
> ```

yes but this is not readily available to the user. Then the user must know the exact implementation with the fields required for the iterator. My goal is to essentially make that easier only.

**Comment by lostella** [comment]
I see. So, what you call `FinitoProblem` couples algorithm options and problem details: this is really what the "iterator" types defined in ProximalAlgorithms are for. What you are proposing is to "standardize" the structure of this object at least partially (as opposed to have every algorithm store it as they want) so that one can access some properties of the state without knowing much about the internal algorithm state representation.

I would improve your interface as follows:

```julia
solver = Finito(args...)
problem = solver(F, g, x0, N, L)
```

This way one can forget about what problem type is associated with a specific algorithm: the right one will just be returned once an algorithm is called on some problem.

Then I would keep the idea that the problem is an iterator, and that you get its sequence of states once it's iterated over. This has the advantage of not having to remember invoking `update!` every time: you just iterate. How to standardize the interface to the problem state? Two ways:

1. Just standardize part of the `state` structure, and e.g. say that it must have a `solution` field

```julia
for state in problem
    println("$(norm(x_star - state.solution))")
end
```

2. Provide standard "getter" functions over problem state types

```julia
for state in problem
    println("$(norm(x_star - solution(state)))")
end
```

**Note:** Since I would keep the iterator structure here, I would really think twice before requiring that each iterator type needs to "manually" handle the iterations counter in the state: that's what `enumerate` is for.

**Comment by pylat** [comment]
@lostella thanks for the comment. My goal is actually to keep the solver the way it is in ProximalAlgorithms and have this additional functionality. Since the function like object style is already being used for the former purpose, I made the new functionality in an admittedly ugly way, I will fix that! 

I see what you are saying. It is really neat to give the iterator itself to the user. My main issue is that with for loop over the iterator, we have to either pass maxit to the iterator, or ask the user to add annoying if statements inside the loop. I assume you mean the former. In that case, the issue is that say I ran the code with maxit = 1000, and am not satisfied and want to run it for another 1000 iterations. Then I have to redefine the whole solver and the iterator structure. This is kinda annoying and wasteful, no? I think this new functionality should not be involved with maxit or any termination criteria. I just want to take one step of the algorithm regardless.
 This is the main motivation to make a separate front say called problem for instance that is essentially unrolling the iterates as enumerate would. In this case if I'm not satisfied after 1000 iterations, I just put `update!(problem)` in another for loop without the need to redefine the whole structure. 
Don't you agree this is more convenient?

**Comment by lostella** [comment]
> In this case if I'm not satisfied after 1000 iterations, I just put update!(problem) in another for loop without the need to redefine the whole structure. Don't you agree this is more convenient?

I'm not sure. What I'm trying to convince you of is that, as long as you iterate over an object, no explicit call to `update!` it is needed: the "update" will happen internally when going from one state to the next. And you can even use the final state to resume iteration: regarding your example (run 1000 iterations, pause, resume and run 1000 more), you can do

```julia
checkpoint = nothing  # just to have it in global scope

for state in take(iterator, 1000)  # the fact that iterator yields its own state is fundamental
    # do stuff
    checkpoint = state
end

for state in take(rest(iterator, checkpoint), 1000)
    # do more stuff
end
```

where this is using `rest`: https://docs.julialang.org/en/v1/base/iterators/#Base.Iterators.rest. Another option (cleaner in my opinion) is to use the `Stateful` iterator type https://docs.julialang.org/en/v1/base/iterators/#Base.Iterators.Stateful:

```julia
stateful_iterator = Iterators.Stateful(iterator)

for state in take(stateful_iterator, 1000)
    # do stuff
end

for state in take(stateful_iterator, 1000)
    # do more stuff, this will resume stateful_iterator from where it was left
end
```

I'm not suggesting that every user should write the above code: one can always wrap the above in some "higher level" interface for the user's convenience, though some flexibility will be gone when using that (unless such interface has a very extensive and expressive set of options). But if one wants, like if they need to do very custom things between iterations (say, plot several frames and make a movie out of it), they can just loop your iterator and access the state the way they want (no call to `update!` involved).

I just believe we're still discussing about iteration and state after all, so the standard iterator interface should be exploited because it's *very* powerful, and supported by quite some tooling in the standard library.

**Comment by lostella** [comment]
@pylat I mean, look at this beauty:

```julia
julia> sl = Iterators.Stateful(1:100)
Base.Iterators.Stateful{UnitRange{Int64},Union{Nothing, Tuple{Int64,Int64}}}(1:100, (1, 1), 0)

julia> for el in Iterators.take(sl, 10)
           println(el)
       end
1
2
3
4
5
6
7
8
9
10

julia> for el in Iterators.take(sl, 10)
           println(el)
       end
11
12
13
14
15
16
17
18
19
20

julia> for el in Iterators.take(sl, 10)
           println(el)
       end
21
22
23
24
25
26
27
28
29
30
```

**Comment by pylat** [comment]
Very nice indeed. I did not know about this. That solves all my concerns. Thanks Lorenzo.
